services:
  pretek:
    container_name: pretek
    build:
      context: .
    image: pretek:latest
    pull_policy: build
    networks:
      - nginx-proxy-manager_default
    restart: unless-stopped

networks:
  nginx-proxy-manager_default:
    external: true